//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_flashlight : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean moveCameraForward
        {
            get
            {
                return SteamVR_Actions.flashlight_moveCameraForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean flashlightClick
        {
            get
            {
                return SteamVR_Actions.flashlight_flashlightClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean beamSizePlus
        {
            get
            {
                return SteamVR_Actions.flashlight_beamSizePlus;
            }
        }
        
        public virtual SteamVR_Action_Boolean freezeBeam
        {
            get
            {
                return SteamVR_Actions.flashlight_freezeBeam;
            }
        }
        
        public virtual SteamVR_Action_Boolean switchMode
        {
            get
            {
                return SteamVR_Actions.flashlight_switchMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean moveCameraBackward
        {
            get
            {
                return SteamVR_Actions.flashlight_moveCameraBackward;
            }
        }
        
        public virtual SteamVR_Action_Boolean beamSizeMinus
        {
            get
            {
                return SteamVR_Actions.flashlight_beamSizeMinus;
            }
        }
    }
}
