//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Boolean p_flashlight_moveCameraForward;
        
        private static SteamVR_Action_Boolean p_flashlight_flashlightClick;
        
        private static SteamVR_Action_Boolean p_flashlight_beamSizePlus;
        
        private static SteamVR_Action_Boolean p_flashlight_freezeBeam;
        
        private static SteamVR_Action_Boolean p_flashlight_switchMode;
        
        private static SteamVR_Action_Boolean p_flashlight_moveCameraBackward;
        
        private static SteamVR_Action_Boolean p_flashlight_beamSizeMinus;
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean flashlight_moveCameraForward
        {
            get
            {
                return SteamVR_Actions.p_flashlight_moveCameraForward.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean flashlight_flashlightClick
        {
            get
            {
                return SteamVR_Actions.p_flashlight_flashlightClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean flashlight_beamSizePlus
        {
            get
            {
                return SteamVR_Actions.p_flashlight_beamSizePlus.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean flashlight_freezeBeam
        {
            get
            {
                return SteamVR_Actions.p_flashlight_freezeBeam.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean flashlight_switchMode
        {
            get
            {
                return SteamVR_Actions.p_flashlight_switchMode.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean flashlight_moveCameraBackward
        {
            get
            {
                return SteamVR_Actions.p_flashlight_moveCameraBackward.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean flashlight_beamSizeMinus
        {
            get
            {
                return SteamVR_Actions.p_flashlight_beamSizeMinus.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.flashlight_moveCameraForward,
                    SteamVR_Actions.flashlight_flashlightClick,
                    SteamVR_Actions.flashlight_beamSizePlus,
                    SteamVR_Actions.flashlight_freezeBeam,
                    SteamVR_Actions.flashlight_switchMode,
                    SteamVR_Actions.flashlight_moveCameraBackward,
                    SteamVR_Actions.flashlight_beamSizeMinus};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.flashlight_moveCameraForward,
                    SteamVR_Actions.flashlight_flashlightClick,
                    SteamVR_Actions.flashlight_beamSizePlus,
                    SteamVR_Actions.flashlight_freezeBeam,
                    SteamVR_Actions.flashlight_switchMode,
                    SteamVR_Actions.flashlight_moveCameraBackward,
                    SteamVR_Actions.flashlight_beamSizeMinus};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.flashlight_moveCameraForward,
                    SteamVR_Actions.flashlight_flashlightClick,
                    SteamVR_Actions.flashlight_beamSizePlus,
                    SteamVR_Actions.flashlight_freezeBeam,
                    SteamVR_Actions.flashlight_switchMode,
                    SteamVR_Actions.flashlight_moveCameraBackward,
                    SteamVR_Actions.flashlight_beamSizeMinus};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.flashlight_moveCameraForward,
                    SteamVR_Actions.flashlight_flashlightClick,
                    SteamVR_Actions.flashlight_beamSizePlus,
                    SteamVR_Actions.flashlight_freezeBeam,
                    SteamVR_Actions.flashlight_switchMode,
                    SteamVR_Actions.flashlight_moveCameraBackward,
                    SteamVR_Actions.flashlight_beamSizeMinus};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_flashlight_moveCameraForward = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/flashlight/in/moveCameraForward")));
            SteamVR_Actions.p_flashlight_flashlightClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/flashlight/in/flashlightClick")));
            SteamVR_Actions.p_flashlight_beamSizePlus = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/flashlight/in/beamSizePlus")));
            SteamVR_Actions.p_flashlight_freezeBeam = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/flashlight/in/freezeBeam")));
            SteamVR_Actions.p_flashlight_switchMode = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/flashlight/in/switchMode")));
            SteamVR_Actions.p_flashlight_moveCameraBackward = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/flashlight/in/moveCameraBackward")));
            SteamVR_Actions.p_flashlight_beamSizeMinus = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/flashlight/in/beamSizeMinus")));
        }
    }
}
